version: "3"

services:
  sut:
    build:
      dockerfile: Dockerfile
      context: ""
    depends_on:
      - db
    environment:
      ENV: test
    command: ["pytest", "tests"]

  db:
    image: "postgres:11.2-alpine"
    environment:
      POSTGRES_PASSWORD: tower_mayday
      POSTGRES_USER: control_tower
    ports:
      - "127.0.0.1:5434:5432"
